[package]
name = "appinsights"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"
description = "Application Insights SDK for Rust"
license = "MIT"
documentation = "https://docs.rs/appinsights"
repository = "https://github.com/dmolokanov/appinsights-rs"

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1.0"
chrono = "0.4"
http = "0.2.0"
uuid = { version = "0.8", features = ["v4"], default-features = false }
reqwest = { version = "0.10", features = ["blocking", "json"], default-features = false }
log = "0.4"
crossbeam-channel = "0.4"
sm = "0.9"

[dev-dependencies]
test-case = "0.3"
env_logger = "0.7"
mockito = { version = "0.22.0", default-features = false }
lazy_static = "1.4"
matches = "0.1"
hyper = { version = "0.13.1" }
tokio = { version = "0.2.9", default-features = false }
futures = { version = "0.3.1", default-features = false }
