[package]
name = "appinsights-contracts-codegen"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
codegen = "0.1.1"
structopt = "0.3.3"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
heck = "0.3.1"
