[package]
name = "appinsights-contracts-codegen"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
codegen = "0.1.3"
structopt = "0.3.21"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.63"
heck = "0.3.2"
